#requires -Version 5.1
<#
.SYNOPSIS
    Create a one-click desktop shortcut for DeepSeek Harness (DSH).

.DESCRIPTION
    Detects the dsh CLI, generates a launcher script, creates a desktop
    shortcut (with the DSH whale icon), and refreshes the Windows icon cache.
    Double-clicking the shortcut starts `dsh web` (if not already running)
    and opens the browser at the DSH web UI.

    Designed to run on any Windows machine with DeepSeek Harness installed.

.PARAMETER ShortcutName
    Display name of the desktop shortcut. Default: DSH 网页启动

.PARAMETER Url
    Web UI address to open. Default: http://127.0.0.1:3080

.PARAMETER Port
    TCP port used to detect whether the server is already running.
    Default: 3080

.PARAMETER LauncherScriptPath
    Where to write the generated launcher script. Default:
    <DSH_HOME or ~/.dsh>\start-web.ps1

.PARAMETER IconPath
    Path to the .ico file used for the shortcut. Default: the bundled
    assets\dsh.ico next to this script; falls back to a generic globe icon.

.PARAMETER Force
    Overwrite an existing shortcut and launcher script without prompting.

.EXAMPLE
    .\scripts\create-shortcut.ps1

.EXAMPLE
    .\scripts\create-shortcut.ps1 -ShortcutName "My DSH" -Url "http://localhost:3080"

.EXAMPLE
    .\scripts\create-shortcut.ps1 -Force
#>
[CmdletBinding()]
param(
    [string]$ShortcutName = 'DSH 网页启动',
    [string]$Url = 'http://127.0.0.1:3080',
    [int]$Port = 3080,
    [string]$LauncherScriptPath = '',
    [string]$IconPath = '',
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# --- Resolve dsh CLI ---------------------------------------------------------
$dshCmd = (Get-Command dsh -ErrorAction SilentlyContinue).Source
if (-not $dshCmd) {
    Write-Error "Could not find the 'dsh' command on PATH.`nInstall DeepSeek Harness first (npm install -g @deepseek-ai/dsh) or add it to PATH."
    exit 1
}
Write-Host "[ok] dsh found: $dshCmd" -ForegroundColor Green

# --- Resolve DSH home --------------------------------------------------------
$dshHome = $env:DSH_HOME
if (-not $dshHome) { $dshHome = Join-Path $HOME '.dsh' }

# --- Resolve desktop (handles OneDrive redirection) --------------------------
$desktop = [Environment]::GetFolderPath('Desktop')
if (-not $desktop) { $desktop = Join-Path $HOME 'Desktop' }
if (-not (Test-Path $desktop)) {
    Write-Error "Desktop folder not found: $desktop"
    exit 1
}
Write-Host "[ok] desktop: $desktop" -ForegroundColor Green

# --- Launcher script ---------------------------------------------------------
if (-not $LauncherScriptPath) {
    $LauncherScriptPath = Join-Path $dshHome 'start-web.ps1'
}
$launcherDir = Split-Path -Parent $LauncherScriptPath
if (-not (Test-Path $launcherDir)) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }

$launcherContent = @"
# start-web.ps1 - generated by dsh-desktop-shortcut
# Starts the dsh web server if needed, then opens the browser.
`$ErrorActionPreference = 'Stop'
`$url  = '$Url'
`$port = $Port

# Already running? Just open the browser.
`$listening = Get-NetTCPConnection -LocalPort `$port -State Listen -ErrorAction SilentlyContinue
if (`$listening) {
    Start-Process `$url
    exit 0
}

# Start the server in its own visible PowerShell window (close it to stop the server).
Start-Process powershell.exe -ArgumentList @(
    '-NoExit','-NoProfile',
    '-Command','`$Host.UI.RawUI.WindowTitle = "DSH Server"; dsh web'
) -WorkingDirectory "`$env:USERPROFILE"

# Wait for the port to come up (up to 90 seconds).
`$deadline = (Get-Date).AddSeconds(90)
while ((Get-Date) -lt `$deadline) {
    if (Get-NetTCPConnection -LocalPort `$port -State Listen -ErrorAction SilentlyContinue) {
        Start-Sleep -Seconds 1
        Start-Process `$url
        exit 0
    }
    Start-Sleep -Milliseconds 500
}

# Timed out: still open the browser so the error is visible there.
Start-Process `$url
exit 1
"@

if (Test-Path $LauncherScriptPath) {
    if ($Force) {
        Write-Host "[..] overwriting launcher script: $LauncherScriptPath" -ForegroundColor Yellow
    } else {
        Write-Host "[..] launcher script exists, updating: $LauncherScriptPath" -ForegroundColor Yellow
    }
}
$utf8Bom = New-Object System.Text.UTF8Encoding($true)
[System.IO.File]::WriteAllText($LauncherScriptPath, $launcherContent, $utf8Bom)
Write-Host "[ok] launcher script: $LauncherScriptPath" -ForegroundColor Green

# --- Icon ---------------------------------------------------------------------
$icon = ''
if ($IconPath -and (Test-Path $IconPath)) {
    $icon = $IconPath
} else {
    $candidate = Join-Path (Split-Path -Parent $PSScriptRoot) 'assets\dsh.ico'
    if (Test-Path $candidate) { $icon = $candidate }
}
$iconLocation = if ($icon) { "$icon,0" } else { "$env:SystemRoot\System32\shell32.dll,13" }

# --- Shortcut ------------------------------------------------------------------
$lnkPath = Join-Path $desktop "$ShortcutName.lnk"
if (Test-Path $lnkPath) {
    if ($Force) {
        Write-Host "[..] overwriting shortcut: $lnkPath" -ForegroundColor Yellow
    } else {
        Write-Host "[..] shortcut exists, updating: $lnkPath" -ForegroundColor Yellow
    }
}
$ws = New-Object -ComObject WScript.Shell
$lnk = $ws.CreateShortcut($lnkPath)
$lnk.TargetPath = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
$lnk.Arguments = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$LauncherScriptPath`""
$lnk.WorkingDirectory = $HOME
$lnk.Description = "Start DeepSeek Harness and open $Url"
$lnk.IconLocation = $iconLocation
$lnk.WindowStyle = 7
$lnk.Save()
Write-Host "[ok] shortcut: $lnkPath" -ForegroundColor Green

# --- Refresh icon cache (best effort) ------------------------------------------
$ie = "$env:SystemRoot\System32\ie4uinit.exe"
if (Test-Path $ie) {
    try { & $ie -show 2>$null | Out-Null } catch { }
}

Write-Host ""
Write-Host "Done. Double-click '$ShortcutName' on your desktop to start DSH and open the web UI." -ForegroundColor Cyan
Write-Host "  URL : $Url" -ForegroundColor Gray
Write-Host "  Icon: $iconLocation" -ForegroundColor Gray
Write-Host "  Tip : the 'DSH Server' console window that opens can be closed to stop the server." -ForegroundColor Gray
